### ISSUE TITLE
Set Maxiumums for Burst Data

### ISSUE THREAD

**Issue by violetteta8** [SacArea-BayDeltaProjects/HydroRDITemplate#18]
Create constants to be populated in the constant table so they can be changed more readily if necessary.  (Ex: MaxParams (number of maximum parameters, not as urgent), MaxBurstCnt (total time (in sec) for burst to run, this also needs to be added to the Burst Datatable)

**Comment by USGSminc** [comment]
Created MaxBurstCnt in constants table. Set to create burst table once MaxBurstCnt is reached. Adjusted burst table and Aquarius table to wait for count = MaxBurstCnt and not 30. MaxParams determined to be unnecessary at this point.
