### ISSUE TITLE
Radios Affecting timing CR1000

### ISSUE THREAD

**Issue by violetteta8** [SacArea-BayDeltaProjects/HydroRDITemplate#37]
CR1000 that had radio active and no VM was skipping scans at CM66. Mark experiences the scan ending late (around 62 seconds) causing skipped scans and missed data. Setting “IsRouter” to FALSE in DevConfig seemed to fix the problem. Let’s investigate this and see if we can incorporate some timers into communications(?).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by USGSminc** [comment]
The router option change worked for one data punch and then proceeded to skip again. Over night it collected a few punches correctly but was caught in the VM loop so long that is normally skipped. Trevor was able to tweak the code to force it to exit the loop and this should be added to make sure the program doesn't lock up if there is no VM. How it was working prior to the radio change and why CM61 is working without a problem (it has the same exact program the CM66 was having trouble with) is a mystery at this point.

**Comment by USGSminc** [comment]
Later this occured at CM61 and sending a new version of the program stopped the cycle. on 20190712 I updated the program at DLC and the VM got caught in a loop and was skipping 15min scans with the burst. We need to put timers everywhere to figure out what is going on.

**Comment by USGSminc** [comment]
This is likely not anything to do with the radio but more to do with the CR1000 acting up with the new program. We have seen this at other stations that have no relation with any radios. Fixing the ADVM loop by sending multiple +++ soft break, or power cycling both the ADVM and DCP and the same time. It seems to be an issue with the ADVM falling out of sync with the DCP following processor heavy demands such as when writing to a new CF card. Thus far we have only seen this on CR1000s. I am closing this issue as we believe we have removed radios as the culprit.
