### ISSUE TITLE
TopBottom WQ Power Cycle

### ISSUE THREAD

**Issue by violetteta8** [SacArea-BayDeltaProjects/HydroRDITemplate#51]
Haven't looked into it too much, but it seemed like the EXO relay was tripping every minute when there was no instrument on board. I put Version 4.1 on a different board with TopBottom = False (and still no instruments hooked up), and it seems to cycle as normal.

Not urgent, at the moment, but should be dealt with as we move forward and need to get these set up for the X2 project (whenever that may happen)...

**Comment by USGSminc** [comment]
Looks like the btm flags are being turned on correctly.  I missed that they are not being reset to false in the cycleWQpower subroutine. I will change that and test it once we have some free time.

**Comment by USGSminc** [comment]
Fixed with version 4.21.
During water quality power cycle had the BtmWQPwrCycleCnt reset to zero to stop infinite reset attempts.
