### ISSUE TITLE
Back up 1 minute dataset 

### ISSUE THREAD

**Issue by jehatfield** [SacArea-BayDeltaProjects/HydroRDITemplate#63]
@violetteta8 @USGSminc What do you guys think about logging 1 minute data on a our backup stage sensors as well? Whether it be a PS2 or an acoustic upbeam or both.. I was thinking it would be useful as a backup in the event something happens to your primary stage sensor during a measurement. Food for thought!

**Comment by USGSminc** [comment]
Great idea. I ran into that problem at CM72 and added that function into the program. That was pre versioning so I don't know exactly when that occurred. It may have been after the program version you have. But it is there, at the end of the 1min data (to avoid us having to change the IvRat json). It does rely on you have selecting the correct stage prime and stage second. Currently it is limited to only those two and not all three. But we could add that if you wish.
